#MF3-50 create ref for Game
zinchenko39/game_powerful_octopuses pull request #23
Opened 2023-10-03 18:14 UTC by b602op

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-10-03 18:38 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
>    let currentGameMap: GameMap = initialMap
Ref исправлен верно, но проблема с картой не решена

2023-10-03 18:40 UTC, b602op commented on packages/client/src/pages/Game/index.tsx
>    let currentGameMap: GameMap = initialMap
@Olegas пожалуйста, можно поподробнее, в чем заключается проблема, если я так и хотел, чтобы от перерендра Game всё заново инициализировать, есть пример?

2023-10-03 18:42 UTC, b602op commented on packages/client/src/pages/Game/index.tsx
>    let currentGameMap: GameMap = initialMap
если я 2 компонента хочу использовать Game на странице -  я же вернусь к этому подходу

2023-10-03 18:49 UTC, b602op commented on packages/client/src/pages/Game/index.tsx
>    let currentGameMap: GameMap = initialMap
в каком случае рисовать 2 компонента - например, для игры в 2 экранах с одной клавиатуры

2023-10-03 18:50 UTC, b602op commented on packages/client/src/pages/Game/index.tsx
>    let currentGameMap: GameMap = initialMap
если у меня будет глобальная переменная для двух Game компонентов - будет конфликт

2023-10-03 19:52 UTC, b602op commented on packages/client/src/pages/Game/index.tsx
>    let currentGameMap: GameMap = initialMap
@Olegas прошу обратить внимание, что просьба данного фикса не спасает нас от неконтролируемых перерендров компонента Game. Так как теперь состояние карты ЛИБО будет сохраняться из игры в игру, либо постоянно возвращаться в определенное состояние

2023-10-04 05:37 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
>    let currentGameMap: GameMap = initialMap
@b602op перерендер компонента не равно рестарту игры. Перерендер может произойти от смены пропов например или какого-то перестроения дерева выше. А рестарт игры это "бизнес-действие". Не надо их замешивать. Рестарт должен делаться явно.

Безусловно, вынос в глобальную область не самый лучший фикс. Особенно если у вас возможно два компонента игры одновременно. Поэтому я и предложил в качестве решения в первую очередь сохранить карту в ref, ну или на крайний случай сделать ее глобальной.

Вынос карты в ref или в глобальную переменную не спасает от перерендеров. Это спасает от сброса карты в случае перерендера. Выше я написал почему перерендер и рестарт игры - это разные вещи и не надо их смешивать.

2023-10-04 05:40 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +  currentGameMap = initialMap
Ничего не поменялось. При перестроении компонента Game карта все равно сбрасывается в начальное состояние.
Что надо сделать
1. Разделить рестарт игры и перерендер компонента. При рестарте игры сбрасывать карту.
2. Вынести карту в ref (глобальная переменная не подойдет т.к. ты говоришь что у вас в проекте может быть две игры одновременно на экране, я не знал об этом при написании предыдущего комментария)

2023-10-04 05:40 UTC, Olegas requested changes
Проблема не решена. Написал подробнее комментарий

2023-10-04 18:52 UTC, b602op commented on packages/client/src/pages/Game/index.tsx
>    let currentGameMap: GameMap = initialMap
@Olegas спасибо, то что нужно, так понятнее стало, для чего разделение и какую цель мы преследуем

2023-10-04 19:21 UTC, Olegas commented
@b602op Вот что я имел ввиду. Не надо складывать на DOM-элементы. Ref можно использовать не только для доступа к DOM
https://github.com/zinchenko39/game_powerful_octopuses/pull/24

2023-10-04 20:24 UTC, b602op commented
@Olegas собственно так я хранилище рефа так и использовал, просто в 1 сразу и привязка к элементу, и состояние карты этого элемента. Вообще в будущем по разделению логики - я планировал поместить состояние игры в стейт редакса (когда редакс будет в проекте) - вот ещё аргумент, не упомянул сразу, извиняюсь

2023-10-04 22:23 UTC, b602op commented
@Olegas 
вот так это выглядет
![image](https://github.com/zinchenko39/game_powerful_octopuses/assets/40558574/bf40cbff-67f7-44ca-aaf0-fb5da6dbee31)

2023-10-05 04:34 UTC, Olegas commented
@b602op я понял, но не надо так делать никогда. Ref надо использовать по документации. Значение должно быть в current и нигде в другом месте. Так получается костыль. React нам гарантирует что в current будет значение, которое сохранится между рендерами. Насчет других полей никто никаких гарантий не давал. Именно по этому надо завести отдельный.

Ок, я вижу мы сейчас поняли друг друга, разобрались как надо и почему как было раньше - не надо. Приму работу, дальше сами с командой решите, переделывать сейчас или оставить до переноса стейта как вы запланировали.

2023-10-05 06:49 UTC, b602op commented
@Olegas спасибо

2023-10-09 22:21 UTC, closed without merging