MF3-58 Настройка Redux
zinchenko39/game_powerful_octopuses pull request #27
Opened 2023-10-05 20:16 UTC by sigarachi

### Какую задачу решаем
Настройка Redux хранилища

2023-10-06 10:56 UTC, gudtae approved these changes

2023-10-07 06:40 UTC, IvanPeleshok commented on packages/client/src/hooks/useUser.ts
> +export const useUser = (): IUser | undefined => {
Для подобных манипуляций предлагаю использовать селекторы из redux-toolkit
https://redux-toolkit.js.org/api/createSelector

2023-10-07 06:44 UTC, IvanPeleshok commented on packages/client/src/pages/singIn/SingIn.tsx
> +      dispatch(apiSlice.util.invalidateTags(['USER']))
Интересное решение, ранее не встречал
Обычно реализуют невалидные теги следующим образом:
https://medium.com/att-israel/common-rtk-query-usage-cont-caching-b72c21196a4b#:~:text=invalidateTags%20%E2%80%94%20This%20part%20is%20the%20trigger%20point%20for%20the%20tag%20invalidation%20(cache%20invalidation).%0AOnce%20this%20is%20attached%20to%20a%20mutation%20endpoint%2C%20the%20listeners%20(endpoints)%20for%20this%20tag%20will%20experience%20cache%20invalidation%20for%20their%20data%2C%20which%20will%20trigger%20another%20fetch%20call.

Имхо, так система кажется более предсказуемой, гибкой, масштабируемой
Предлагаю ознакомиться и поправить

2023-10-07 06:46 UTC, IvanPeleshok requested changes
Замечательная работа, отлично постарались!
Есть небольшие замечания (если не согласны, можем обсудить :))
Предлагаю доработать

2023-10-07 08:10 UTC, sigarachi commented on packages/client/src/pages/singIn/SingIn.tsx
> +      dispatch(apiSlice.util.invalidateTags(['USER']))
К сожалению, medium открываться не хочет :)

2023-10-07 08:11 UTC, sigarachi commented on packages/client/src/hooks/useUser.ts
> +export const useUser = (): IUser | undefined => {
вообще там уже есть селектор в коде, попробую просто на него поменять

2023-10-07 08:17 UTC, sigarachi commented on packages/client/src/hooks/useUser.ts
> +export const useUser = (): IUser | undefined => {
Я просто не совсем уверен как правильно сделать селектор для rtk query

2023-10-07 08:18 UTC, sigarachi commented on packages/client/src/hooks/useUser.ts
> +export const useUser = (): IUser | undefined => {
В документации у них обычные стейты, с ними все понятно

2023-10-07 08:34 UTC, sigarachi commented on packages/client/src/pages/singIn/SingIn.tsx
> +      dispatch(apiSlice.util.invalidateTags(['USER']))
Открылось через впн, я так понял предложение сделать через мутации, которые будут инвалидировать тэги?

2023-10-07 20:31 UTC, IvanPeleshok commented on packages/client/src/hooks/useUser.ts
> +export const useUser = (): IUser | undefined => {
Действительно, немного неочевидная история
Ваше решение выглядит отлично 🚀

2023-10-07 20:35 UTC, IvanPeleshok approved these changes
Замечательная работа!
Чувствуется опыт за плечами, продолжайте в том же духе 🚀 
Поздравляю, работа принята!

2023-10-08 06:31 UTC, merged