Feature/mf3 55
zinchenko39/game_powerful_octopuses pull request #28
Opened 2023-10-07 23:11 UTC by zinchenko39

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-10-08 18:11 UTC, sigarachi approved these changes
ok

2023-10-09 12:18 UTC, IvanPeleshok commented on packages/client/sw.ts
Всё замечательно, но есть небольшое предложение:
Предлагаю переписать колбеки then / catch на try / catch + async / await
Так код будет намного чище и читаемее

2023-10-09 12:20 UTC, IvanPeleshok requested changes
Проделана огромная работа, отлично потрудились! 🚀 
Есть небольшое замечание, предлагаю доработать

Хорошего дня :)

2023-10-09 12:20 UTC, IvanPeleshok commented on packages/client/sw.ts
https://learn.javascript.ru/async-await

2023-10-10 18:12 UTC, merged