Feature/mf3 57
zinchenko39/game_powerful_octopuses pull request #30
Opened 2023-10-09 06:53 UTC by b602op

[фул скрин](https://linear.app/powerful-octopuses/issue/MF3-57/dobavit-minimum-odno-web-api)

2023-10-09 10:34 UTC, gudtae approved these changes
Заходит и выходит из полного экрана, все отлично работает

2023-10-09 12:41 UTC, IvanPeleshok commented on packages/client/src/pages/GameMenu/index.tsx
> +      document.documentElement.requestFullscreen()
Данный метод поддерживается не везде https://caniuse.com/?search=requestFullscreen

Предлагаю ознамиться со следующим решением, которое поддерживается во всех барузерах

https://stackoverflow.com/questions/13503016/how-to-enable-ie-full-screen-feature-like-firefox-and-chrome#:~:text=sheelpriy%20answer%20is%20good%20with%20a%20small%20change%2C%20successfully%20tested%20on%20chrome%2C%20firefox%2C%20ie%2C%20safari%20and%20opera%20(all%20last%20version)

2023-10-09 12:42 UTC, IvanPeleshok commented on packages/client/src/pages/GameMenu/index.tsx
> +enum FullScreenText {
Замечательно, что вынесли в константу, но я бы предложил хранить их в отдельном модуле, где хранятся другие константы для того, чтобы была возможно переиспользовать (к примеру, в тестах)

2023-10-09 12:43 UTC, IvanPeleshok commented on packages/client/src/pages/GameMenu/index.tsx
> +  const handleClickFullScreen = () => {
Предлагаю вынести функционал самой логики показа полноэкранного режима в отдельный модуль

В handleClickFullScreen можно вызывать этот метод, либо сделать в виде кастомного хука

В компоненте же будет логики, легче читать код

2023-10-09 12:44 UTC, IvanPeleshok requested changes
Проделана огромная работа, отлично постарались! 🚀 

Есть небольшие замечания: предлагаю доработать

Хорошего дня :)

2023-10-10 08:39 UTC, b602op commented on packages/client/src/pages/GameMenu/index.tsx
> +enum FullScreenText {
@IvanPeleshok исправил. Но по личным взглядам предпочитаю придерживаться правила - выносить только когда тип по факту используется в нескольких местах проекта.

2023-10-10 08:42 UTC, b602op commented on packages/client/src/pages/GameMenu/index.tsx
> +  const handleClickFullScreen = () => {
@IvanPeleshok улучшил

2023-10-10 10:16 UTC, IvanPeleshok approved these changes
Отличная работа!
Замечательно реализовали функционал!
Поздравляю, апрув 🚀 

Хорошего дня :)

2023-10-10 10:18 UTC, merged

2023-10-10 10:22 UTC, IvanPeleshok commented on packages/client/src/pages/GameMenu/index.tsx
> +      document.documentElement.requestFullscreen()
Это учебный проект - моя компетенция подсветить для вас некоторые моменты, которые мне показались важными

В ваших силах рассказать мне о том, что у вас есть сомнения в том или ином замечании, где мы придём к консенсусу

Хочу заметить, что вы отлично с этим справились :)

Действительно, getContext не взлетит в IE
При необходимости обработать этот кейс - как вариант - показать заглушку, что данный функционал не поддерживается
Можете записать в тех.долг проекта