Feature/mf3 66
zinchenko39/game_powerful_octopuses pull request #44
Opened 2023-11-09 09:27 UTC by zinchenko39

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-11-10 12:06 UTC, sigarachi commented
большое количество файлов, которые не относятся к твоей задаче

2023-11-10 15:29 UTC, sigarachi commented on packages/server/db.ts
> +      host: 'postgres',
надо бы вынести это в env, потому что локально проще работать с localhost

2023-11-10 17:20 UTC, zinchenko39 commented on packages/server/db.ts
> +      host: 'postgres',
Согласен! Хорошее замечание, перенес.

2023-11-11 07:23 UTC, sigarachi approved these changes
ok

2023-11-11 12:03 UTC, Olegas commented on Dockerfile.server
> +CMD ["/wait-for.sh", "postgres:5432", "--", "node", "/app/index.js"]
Круто что проверяешь старт postgres через wait-for, но стоит перенести контроль за запуском контейнера postgres в docker-compose. Иначе контейнер сервера явно знает о том, где у него база и это захардкожено в докерфайле. Правильно передавать параметры подключения к БД через переменные окружения (что бы этот контейнер можно было запустить где угодно) а в docker-compose надо выставить зависимость от контейнера БД и добавить туда же проверку на то, что сервер БД запустился

2023-11-11 12:03 UTC, Olegas commented on docker-compose.yml
> +  client:
У этого контейнера надо выставить зависимость от server

2023-11-11 12:04 UTC, Olegas commented on docker-compose.yml
> +    depends_on:
Здесь зависимость от postgres уже есть и это хорошо, осталось добавить сюда проверку что контейнер запустился и "здоров"

2023-11-11 12:05 UTC, Olegas requested changes
Добрый день. Есть замечания по реализации. Оставил подробные комментарии в коде

2023-11-13 08:45 UTC, Olegas approved these changes
Работа принята. Отлично получилось!

2023-11-13 09:09 UTC, merged