MF3-71 Смена темы на бэке
zinchenko39/game_powerful_octopuses pull request #45
Opened 2023-11-10 14:23 UTC by sigarachi

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-11-10 20:52 UTC, zinchenko39 reviewed
Выглядит отлично, только нужно поправить с HOST

2023-11-10 20:52 UTC, zinchenko39 commented on packages/server/db.ts
'localhost' так же можно вынести в .env

2023-11-11 09:32 UTC, zinchenko39 approved these changes
LGTM

2023-11-11 12:18 UTC, Olegas commented on packages/server/controllers/theme.controller.ts
> +      if (!body.userId || !body.theme) {
Есть ли у вас уже мидлвара на сервере, которая проверяет авторизацию? Если да то тут нужно брать данные о текущем пользователе не из тела запроса, а от данных модлвары. Иначе я смогу менять тему другому пользователю.

2023-11-11 12:20 UTC, Olegas commented on packages/server/models/theme.model.ts
> +  userId: {
1. На это поле должен быть сделан индекс, т.к. тему всегда ищем от пользователя
2. Индекс должен быть уникальный, т.к. иначе нет гарантии что для одного пользователя не будет создано несколько записей

2023-11-11 12:23 UTC, Olegas commented on packages/server/controllers/theme.controller.ts
> +      Theme.findOne({ where: { userId: params.userId } }).then(async function (
Такая проверка (findOne + create) не будет нормально работать в случае конкурентных запросов. Грубо говоря - два запрос приходят на пустую базу, оба видят что темы для пользователя нет и оба его создают. Для решения подобных вещей лучше использовать метод upsert. А в случае с чтением темы можно не создавать в БД ничего а просто возвращать дефолт, до тех пор пока пользователь не решит сменить настройку

2023-11-11 12:24 UTC, Olegas requested changes
Добрый день.
Есть в решении есть проблемы. Написал подробно комментарии в коде.
Требуется доработка.

2023-11-12 17:22 UTC, Olegas approved these changes
Работа принята

2023-11-12 17:28 UTC, merged